### ISSUE TITLE
Honest question : explain your disagreement with Facebook's JSX

### ISSUE THREAD

**Issue by DjebbZ** [substack/hyperx#2]
Hello,

In the README, you say disagree with http://facebook.github.io/jsx/#why-not-template-literals. Can you give more details ? I'm questioning the pros and cons of JSX, template literals and simple functions. Your input could be valuable in my reflexion.

Thanks in advance !

**Comment by substack** [comment]
JSX isn't part of the javascript language, so it always requires special configuration and extra tooling to work properly. Often, these extra tools and configuration are built around a particular stack, like react, which makes it more difficult to use them in isolation. Configuring jsx tools to support non-react options like virtual-dom/main-loop (which I like better) was more difficult than it ought to be. With less coupled tooling, we can experiment more freely and arrive on better solutions.

With a tagged template string function, you can pass in any configuration details and argument in your code instead of configuring your build pipeline, which I think is much more flexible and you can use template strings natively in node without any compile steps.

**Comment by DjebbZ** [comment]
Thanks a lot.
